#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_save_sensor_data_v1:
  path: /v1/saveSensorData
  controller: App\Controller\IncomeDataController::storeSensorData

get_map_data:
  path: /v1/getMapData
  controller: App\Controller\FrontController::getMapData
