#index:
#    path: /
#    controller: App\Controller\DefaultController::index

api_save_sensor_data_v1:
  path: /api/v1/saveSensorData
  controller: App\Controller\IncomeDataController::storeSensorData
